### ISSUE TITLE
FileManager Prevents rutorrent from Loading (FreeNAS 9.3 in FreeBSD 9.3 Jail)

### ISSUE THREAD

**Issue by thadius856** [nelu/rutorrent-thirdparty-plugins#1]
As the title says, I'm unable to get FileManager to work with on FreeNAS 9.3 in a FreeBSD jail. I'd like to help in whatever way I can to troubleshoot to get this working on FreeBSD.

rtorrent 0.9.4
libtorrent 0.13.4
rutorrent 3.6 (svn $Rev: 2404 $)

I placed all 4 plugins in the plugin directory. Each was chmod'd recursively to 755 and chown'd recursively to the rtorrent user. $topDirectory is set in rutorrent/conf/config.php. The directory it points to (and all of its contents) are owned by the rtorrent user and 755.

When I loading rutorrent, it starts loading plugins, then fails like so:

> [28.03.2015 11:18:49] WebUI started.
> [28.03.2015 11:18:51] Bad response from server: (500 [error,getplugins])

I've temporarily chmod'd all four plugins to 000 so I can continue using rutorrent in the meantime. Any ideas for things to check?

**Comment by nelu** [comment]
Can you check your php error log? Dont chown, otherwise the webserver user wont be able to read the plugin files. chmod only /filemanager/scripts to 775

**Comment by thadius856** [comment]
Sure thing. Had to fix a few minor php items (most notably date.timezone) which were cluttering up the logs, but here ya go.

From `httpd-error.log`:

> [Sun Mar 29 17:59:17 2015] [notice] caught SIGTERM, shutting down
> [Sun Mar 29 17:59:18 2015] [warn] Init: Session Cache is not configured [hint: SSLSessionCache]
> [Sun Mar 29 17:59:18 2015] [notice] Digest: generating secret for digest authentication ...
> [Sun Mar 29 17:59:18 2015] [notice] Digest: done
> [Sun Mar 29 17:59:19 2015] [notice] Apache/2.2.29 (FreeBSD) mod_scgi/1.12 PHP/5.3.29 with Suhosin-Patch mod_ssl/2.2.29 OpenSSL/0.9.8za-freebsd DAV/2 configured -- resuming normal operations
> [Sun Mar 29 17:59:31 2015] [error] [client 192.168.192.168] PHP Warning:  require_once(/usr/local/www/rutorrent-users/sanitized/rutorrent/plugins/fileupload/../filemanager/xmlfix.php): failed to open stream: No such file or directory in /usr/local/www/rutorrent-users/sanitized/rutorrent/plugins/fileupload/init.php on line 4, referer: http://192.168.0.1/sanitized/rutorrent/
> [Sun Mar 29 17:59:31 2015] [error] [client 192.168.192.168] PHP Fatal error:  require_once(): Failed opening required '/usr/local/www/rutorrent-users/sanitized/rutorrent/plugins/fileupload/../filemanager/xmlfix.php' (include_path='.:/usr/local/share/pear') in /usr/local/www/rutorrent-users/sanitized/rutorrent/plugins/fileupload/init.php on line 4, referer: http://192.168.0.1/sanitized/rutorrent/

Edit: Sorry about the delay. Today's been a hectic day. I should be a lot more available for quick responses moving forward.

**Comment by thadius856** [comment]
Any ideas?

**Comment by nelu** [comment]
You can remove the fileupload plugin, since its the one causing the error: (in /usr/local/www/rutorrent-users/sanitized/rutorrent/plugins/fileupload/init.php on line )
