### ISSUE TITLE
FILE MANAGER: Failed to get directory contents

### ISSUE THREAD

**Issue by boyriot** [nelu/rutorrent-thirdparty-plugins#10]
I've tried on debian, ubuntu and it's working. today I moved to centos but I can't get it work. Did I miss some steps?

**Comment by From2750** [comment]
funny. i try in Debian and i get  the error 
FILE MANAGER: Failed to get directory contents

what did you do?

**Comment by boyriot** [comment]
I did nothing, just install manually.

**Comment by SkyREgit** [comment]
**From2750** Read very attentively https://github.com/nelu/rutorrent-thirdparty-plugins

**Comment by boyriot** [comment]
where is plugins/filemanager/scripts/sucmd.sh ?
I couldn't find it

**Comment by samad909** [comment]
I am seeing the same issue on Alpine linux. It works fine on Debian.
The file sucmd.sh doesnt exist on the Debian install, but filemanager works without any issues.

Update - ruTorrent error log shows that execute_capture fails with a faultCode of -503, Bad return code.

**Comment by romancin** [comment]
Same problem here on Alpine Linux. For reference I solved it installing findutils:
apk add --no-cache findutils

**Comment by TMTYD** [comment]
```
[03.12.17 09:20:36] Status: 200 OK
Content-Type: text/xml
Content-Length: 296

<?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
<fault>
<value><struct>
<member><name>faultCode</name>
<value><i4>-503</i4></value></member>
<member><name>faultString</name>
<value><string>Bad return code.</string></value></member>
</struct></value>
</fault>
</methodResponse>

[03.12.17 09:24:52] <?xml version="1.0" encoding="UTF-8"?><methodCall><methodName>execute.capture</methodName><params>
<param><value><string></string></value></param>
<param><value><string>find</string></value></param>
<param><value><string>/media/</string></value></param>
<param><value><string>-mindepth</string></value></param>
<param><value><string>1</string></value></param>
<param><value><string>-maxdepth</string></value></param>
<param><value><string>1</string></value></param>
<param><value><string>-printf</string></value></param>
<param><value><string>%y\t%f\t%s\t%C@\t%#m\n</string></value></param>
</params></methodCall>
[03.12.17 09:24:52] Status: 200 OK
Content-Type: text/xml
Content-Length: 296

<?xml version="1.0" encoding="UTF-8"?>
<methodResponse>
<fault>
<value><struct>
<member><name>faultCode</name>
<value><i4>-503</i4></value></member>
<member><name>faultString</name>
<value><string>Bad return code.</string></value></member>
</struct></value>
</fault>
</methodResponse>
```

The plugin FileManager stops working, in the log of Rutorrent, FILE MANAGER: listing directory content failed:

**Comment by nelu** [comment]
functionality not supported anymore. try the new filemanager in the meantime
