### ISSUE TITLE
FileShare: Error while generating links asynchronously

### ISSUE THREAD

**Issue by MervinB** [nelu/rutorrent-thirdparty-plugins#11]
When you make multiple requests at the time, it generates only one link (the last one requested in the timeline)

The error is in this file:

https://github.com/nelu/rutorrent-thirdparty-plugins/blob/stable/fileshare/share.class.php

``` php
    protected function load() {
        if(!is_file($this->datafile) && !$this->write()) {die('Failed to write file');}

        if(($rf = file_get_contents($this->datafile)) === FALSE) {die('Failed to load data');}
        $this->data = unserialize($rf);
    }
    private function write() {
        return (file_put_contents($this->datafile, serialize($this->data)) !== FALSE);
    }
```

these functions are load and overwritten the log file without taking into account the concurrency.

**Comment by nelu** [comment]
i will add a background to the modal window to prevent multiple actions from the same session, this wont cure the serverside issue

**Comment by nelu** [comment]
plugin deprecated. try the new filemanager plugin
