### ISSUE TITLE
Only show deafult path

### ISSUE THREAD

**Issue by enoch85** [nelu/rutorrent-thirdparty-plugins#17]
Hi!

Thanks for a great plugin. I'm wondering of it's possible to set a default path so that when you open Filemanager, only that path is shown..?

I want his because I don't want my whole root to be shown. 

Thank you in advance!

**Comment by enoch85** [comment]
Found it, it's in `/var/www/ruTorrent/conf/config.php`

```
$topDirectory = '/media/plex/downloads';
```

**Comment by j79** [comment]
Hi,

Thanks for your contribution.

I tried to add this line and restart rutorrent but file manager keep presenting the home path of the user who has launched rtorrent.

I tried to add a link in my home folder but filemanager return a permission issue. I tried to chmod 77 a test directory but still the same.

Any idea for me ?

Thanks

jé'

**Comment by enoch85** [comment]
Sorry, this worked for me.

**Comment by j79** [comment]
no problem :)
At the end I've bypassed my problem creating a symlink in the default download folder.

Jérôme
