### ISSUE TITLE
FileManager not able to follow symlink

### ISSUE THREAD

**Issue by akzkak** [nelu/rutorrent-thirdparty-plugins#18]
Setup FileManager and it runs perfect, but its just not able to follow symlinks correctly. 

Get the following error:
`No such file/dir - /home/owner/stuff / Permission Denied`

However ruTorrent have no problems accessing the same symlink and it can read files and work in the folder just fine.

Did of course `chmod 755 plugins/filemanager/scripts/*` and its able to mv, copy and unpack etc without a problem, but following a symlink is no go.
Also made a test symlink from a folder to a destination folder from where FileManger work without a problem in both, but same error.

**Comment by xxx31fr** [comment]
Hello,
I've the same issue and would like to know how to filemanager plugin can followsymlink.

Thanks.

**Comment by nelu** [comment]
It wont work. Its a security breach. No plan for symlink support
