### ISSUE TITLE
unable to set permission

### ISSUE THREAD

**Issue by Quickboxfan** [nelu/rutorrent-thirdparty-plugins#21]
can u please help me setting in permission

i m in cd /var/www/rutorrent/plugins setting up permission i guess i m doing something wrong,i may require command line help,please help me 

i have install "svn checkout https://github.com/nelu/rutorrent-thirdparty-plugins.git" in cd /var/www/rutorrent/plugins

can u explain me in detail what shoudl i do next

i m new to command line but just know few basics about that,so require your help :)

**Comment by TMTYD** [comment]
my plugin folder have the rights 775 and user:group ist www-data
