### ISSUE TITLE
How to solve this ? 

### ISSUE THREAD

**Issue by mrlongshen** [nelu/rutorrent-thirdparty-plugins#26]
1.  filemanager: Plugin will not work. Webserver user can't access external program (unzip).
2. fileshare: Plugin will not work. It requires plugin(s) filemanager
3. fileupload: Plugin will not work. It requires plugin(s) filemanager
4. fileupload: Plugin will not work. rTorrent user can't access external program (plowup).

**Comment by artyuum** [comment]
Really late reply but this might help others people.

You need to set the path to these tools.
You can get the path with the following commands : 
`which rar`
`which zip`
`which unzip`
`which tar`
`which gzip`
`which bzip2`
`which plowup`

For filemanager (here is a sample of my file for example) : 
`sudo nano plugins/filemanager/conf.php`
```php
$pathToExternals['rar'] = '/usr/bin/';
$pathToExternals['zip'] = '/usr/bin/';
$pathToExternals['unzip'] = '/usr/bin/unzip';
$pathToExternals['tar'] = '/bin/tar';
$pathToExternals['gzip'] = '/bin/gzip';
$pathToExternals['bzip2'] = '/bin/bzip2';
```

**Comment by mrlongshen** [comment]
Thanks. It works fine.

**Comment by Merlincool** [comment]
This plowup doesn't work this way,I couldn't get that fixed mine is located in /bin/plowup

**Comment by LiranYzhak** [comment]
> This plowup doesn't work this way,I couldn't get that fixed mine is located in /bin/plowup

run "apt-get install plowshare"
