### ISSUE TITLE
Stop showing hidden files will not stick.

### ISSUE THREAD

**Issue by Hemicrusher** [nelu/rutorrent-thirdparty-plugins#27]
Hello

I have "show hidden files" unchecked and it works, yet when I go back into rutorrent, hidden files are shown again. If I check the box, and uncheck it, hidden files are hidden again, yet a relog into rutorrent shows the files again even though the box is still unchecked.

Another thing, where does rutorrent plugin folder install to? /var/www does not have the rutorrent directory where I assume it should be as every install instructions I can find shows it should be there.

Thanks.

**Comment by nelu** [comment]
plugin deprecated. try the new filemanager plugin
