### ISSUE TITLE
Rutorrent Dropdown Menu

### ISSUE THREAD

**Issue by SSoft7** [nelu/rutorrent-thirdparty-plugins#3]
Hello, Please check this http://postimg.org/image/n6wykg861/

the Dropdown option is in too lower portion their is no way to scroll. Please can you fix it ?? please reply

**Comment by nelu** [comment]
Does it occur in other table tabs like Files ?

**Comment by SSoft7** [comment]
there is no option for upload in Files Tab http://postimg.org/image/ykjhvniop/ 

Other Dropdown Options do the same thing,I mean these dropdowns are not dynamic ,for other things its manageable, but with fileupload,there is lot of filehost, hard to select,please fix .thank you.

**Comment by SSoft7** [comment]
Hello, Please Any Fix?
