### ISSUE TITLE
Solving the problem with unable to open up the directory 

### ISSUE THREAD

**Issue by marinefargo** [nelu/rutorrent-thirdparty-plugins#32]
Hi

Recently I've updated the PHP and suddenly filemanager was unable to load the directory. An I got this message as the result :
FILE MANAGER: Failed to get directory contents : /

I remember I've read once there is a way to overcome this problem by changing a function in one of the php files, but I cannot nither remember the PHP file name nor the function.

Could anyone help me with this matter, please?

Thanks a lot

**Comment by WagnerGMD** [comment]
https://github.com/nelu/rutorrent-thirdparty-plugins/issues/29
Hi,

one advice : take a look @marinefargo at the last reply by **Micdu70** (and no I didn't try yet because I'm busy IRL and it was discover only yesterday).
