### ISSUE TITLE
There is fileupload supported from rutorrent gui

### ISSUE THREAD

**Issue by Merlincool** [nelu/rutorrent-thirdparty-plugins#43]
I have created topic here https://github.com/mcrapet/plowshare-modules-legacy/issues/223

Assuming it's modules issue but I don't think so,because I could easily upload files from seedbox terminal but not through seedbox gui.

You will find all details I have mentioned,what I did so far.Please read first and third post by me.

I have written complete description with screenshots.

I do have a guess that I have to put some owner rights,can you please confirm what I need to do.

This post here says some permission change https://mondedie.fr/d/7502-evenements-rtorrent-plowup/22

I am not doing as per say because I have no idea that how permission set up actually works,affects my linux and In trial and error I may end you screwing some other functions which might cause my rtorrent to malfunction.So I need to be sure what I am supposed to do,I am learning Linux at the moment.I am from non IT sector and dealing with Linux is my new learning and I am enjoying.

I am insecure to give any rights or any changes because I don't know what that exactly means and to make some of my plugins work I may create breach in my security,to avoid that I am asking you what I need to do so that fileupload from rutorrent works well.It will be nice if you could give brief explanation about what you are telling me to do and what does it affects my system.I have started learning Linux and I am loving.

PS: my sudo have ssh login privileged.

**Comment by nelu** [comment]
functionality not supported anymore. try the donate button for this plugin development
