### ISSUE TITLE
Please update Readme with better installachion info

### ISSUE THREAD

**Issue by Abe-Telo** [nelu/rutorrent-thirdparty-plugins#45]
Please update Readme with full path to Dir The clone githib did not work. 
/var/www/html/ruTorrent/plugin/filemanger 
/var/www/html/ruTorrent/plugin/fileshare
/var/www/html/ruTorrent/plugin/fileupload
/var/www/html/ruTorrent/plugin/mediastream

As well please provide better instructions with FileManger, fileshare 

Add instructions for  fileupload (If needed) I am getting a error 
 fileupload: Plugin will not work. rTorrent user can't access external program (plowup).

Also for me fileshare Link is not working I am getting a Invalid link.

**Comment by Merlincool** [comment]
I think you are using rtorrent under username or may be rtinst version of rtorrent?

This is to install plowshare and plowup with modules.

From Source:

mkdir -p ~/plowshare
cd ~/plowshare
git clone https://github.com/mcrapet/plowshare.git
cd plowshare
make install

And modules:

mkdir -p ~/.config/plowshare/modules.d
cd ~/.config/plowshare/modules.d
curl -L -k https://github.com/mcrapet/plowshare-modules-legacy/archive/master.tar.gz | tar zxf -
mv plowshare-modules-legacy-master legacy

If you are using under username you have to install them using sudo with non-root user

For fileshare.php even I fall short of knowledge how to create symlink. I use rtinst in my rutorrent.

**Comment by nelu** [comment]
plugin deprecated. try the new filemanager plugin
