### ISSUE TITLE
Fileupload plugins don't work

### ISSUE THREAD

**Issue by Merlincool** [nelu/rutorrent-thirdparty-plugins#48]
Since two days the fileupload plugins is not getting installed. I am trying to set up other seedbox but don't find  way it's working? Is there some update lacking?

**Comment by Merlincool** [comment]
https://i.postimg.cc/VNTnCRcw/IMG-20190921-031109.png

I have tried fresh on two different seedboxes

**Comment by nelu** [comment]
this functionality is now deprecated

**Comment by Merlincool** [comment]
> this functionality is now deprecated

Thanks for reply but I still like to use it. And it's working on 1fichier hosting and it's fine for me.
