### ISSUE TITLE
Filemanager plugin doesn't create screenshots with the latest 3.7 ruTorrent

### ISSUE THREAD

**Issue by bStyler** [nelu/rutorrent-thirdparty-plugins#8]
Greetings,

Thank you for the continuous development of this great plugin!

I've been installing filemanager plugin on the latest ruTorrent 3.7 on Ubuntu 15.04

and while testing all the functionalities of the plugin I noticed that the screenshots option doesn't work (screenshots attached below):
![280df40bac554999c906ebc65c9f69ab](https://cloud.githubusercontent.com/assets/7829256/9270587/9486a158-427b-11e5-9876-6489ec4e6ca6.png)
![5cc6cc04596bf9e771fd3db095a62d72](https://cloud.githubusercontent.com/assets/7829256/9270588/9487cc86-427b-11e5-9efa-58cc3c20891d.png)

[14.08.2015 11:51:20] File Manager ERROR: undefined - 200 SyntaxError: Unexpected end of input
[14.08.2015 11:51:20] File Manager ERROR: undefined - 500 Internal Server Error

I'm assuming that this is something that is related to ffmpeg or me not having the right version of it,
Please advise.

**Comment by ghost** [comment]
did you fix that problem?

**Comment by bStyler** [comment]
Unfortunately, I haven't. Still hoping that someone can pitch in a solution.

**Comment by alixcan** [comment]
First create a torrent file then go to files tab and try it again ;)
![screenshot_4](https://user-images.githubusercontent.com/652539/31321975-dc80ef5e-ac96-11e7-8dc7-79f5888567ce.png)

**Comment by nelu** [comment]
plugin deprecated. try the donate button for this plugin development
